[project]
name = "titanicml"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.7.0",
    "matplotlib>=3.10.7",
    "notebook>=7.5.0",
    "pandas>=2.3.3",
    "pandas-stubs==2.3.3.251201",
    "seaborn>=0.13.2",
]
